Repository YAPP-Github/20th-Android-Team-1-BE, pull requests merged in 2022-08, with the labels that each got.

#81 [75-FEAT] 오늘 확정된 약속 조회 API
  controllers/promise-controller.ts
  utils/time.ts
Labels: ✨ FEAT

#89 [88-FEAT] 카테고리 타입 추가
  dtos/category/response.ts
Labels: ✨ FEAT

#87 [82-FIX&83-FIX] 컬러값 매칭 버그 픽스 및 확정된 약속 날짜 처리 관련 버그 픽스
  constants/number.ts
  constants/nums.ts
  services/event-service.ts
  services/promise-service.ts
  services/promise-user-service.ts
  services/promising-service.ts
Labels: 🐞 BUG

#90 [84-REFACTOR] 약속 제안 및 확정된 약속 참여자 배열 정렬 처리
  controllers/promising-controller.ts
  services/promise-user-service.ts
  services/promising-service.ts
  utils/array.ts
Labels: 🚧 REFACTOR
