Repository YAPP-Github/20th-Android-Team-1-BE, pull requests merged in 2022-06, with the labels that each got.

#24 [23-FEAT] 데이터 모델 수정
  models/Event.ts
  models/Promising.ts
  models/Time.ts
  models/category-keyword.ts
  models/event.ts
  models/index.ts
  models/promise.ts
  models/promising.ts
  models/time.ts
  models/user.ts
Labels: 📄 DOCS, ✨ FEAT

#25 [14-DEPLOY] Github Action 자동 배포 구성
  .github/workflows/deploy.yml
  Dockerfile
  app.ts
  controllers/user-controller.ts
  models/category-keyword.ts
  models/event.ts
  models/index.ts
  models/promise-user.ts
  models/promising.ts
  models/time.ts
  models/user.ts
  routes/user-router.ts
Labels: 📢 DEPLOY

#26 [14-DEPLOY] Github Action 스크립트 수정
  .github/workflows/deploy.yml
  Dockerfile
  tsconfig.json
Labels: 📢 DEPLOY

#27 [15-FEAT] 약속 제안 생성
  app.ts
  controllers/promising-controller.ts
  package-lock.json
  package.json
  routes/user-router.ts
  services/promising-service.ts
  tsconfig.json
  utils/array.ts
  utils/time.ts
Labels: ✨ FEAT

#28 [13-FEAT] 사용자 회원가입 및 인증 미들웨어 구현
  .eslintrc.json
  app.ts
  controllers/user-controller.ts
  dtos/auth/request.ts
  dtos/user/request.ts
  dtos/user/response.ts
  middlewares/auth.ts
  models/index.ts
  models/user.ts
  package-lock.json
  package.json
  services/user-service.ts
  tsconfig.json
Labels: ✨ FEAT

#31 [15-FEAT] promising DTO 생성
  controllers/promising-controller.ts
  dtos/promising/request.ts
  dtos/promising/response.ts
  services/promising-service.ts
Labels: ✨ FEAT

#32 [30-FEAT] 에러 핸들러 구현하기
  app.ts
  controllers/promising-controller.ts
  controllers/user-controller.ts
  middlewares/auth.ts
  package-lock.json
  services/promising-service.ts
  services/user-service.ts
  utils/error.ts
Labels: ✨ FEAT

#38 [36-FEAT] 약속 제안 확정 API 구현
  controllers/promising-controller.ts
  controllers/user-controller.ts
  dtos/category/response.ts
  dtos/promise/response.ts
  middlewares/auth.ts
  middlewares/error.ts
  models/alarm.ts
  models/event.ts
  models/promise-user.ts
  models/promise.ts
  models/promising.ts
  models/time.ts
  models/user.ts
  package-lock.json
  package.json
  services/auth-service.ts
  services/event-service.ts
  services/promise-service.ts
  services/promising-service.ts
  services/user-service.ts
  utils/error.ts
  utils/time.ts
Labels: 🚧 REFACTOR, ✨ FEAT

#39 [35-FEAT] 제안 중인 약속 리스트 조회 기능 구현
  controllers/promising-controller.ts
  dtos/promising/request.ts
  services/promising-service.ts
Labels: ✨ FEAT

#45 [41-FEAT] 약속 제안 응답 시간 조회 구현
  constants/color-index.json
  constants/color.json
  controllers/promising-controller.ts
  controllers/user-controller.ts
  dtos/promise/response.ts
  dtos/promising/response.ts
  dtos/user/response.ts
  services/promising-service.ts
  tsconfig.json
  utils/time.ts
Labels: ✨ FEAT
