Repository YAPP-Github/20th-Android-Team-1-BE, pull requests merged in 2022-07, with the labels that each got.

#49 [47-FEAT] 약속 제안 응답 날짜 저장 테이블 생성
  app.ts
  controllers/promising-controller.ts
  dtos/promising/request.ts
  middlewares/error.ts
  models/index.ts
  models/promising-date.ts
  services/promising-service.ts
  utils/error.ts
  utils/time.ts
Labels: 🚧 REFACTOR, ✨ FEAT

#53 [52-DEPLOY] 필요 파일 카피 스크립트 추가
  Dockerfile
  package.json
  tsconfig.json
Labels: 🐞 BUG, 📢 DEPLOY

#54 [51-FEAT] 약속 제안 카테고리 목록 조회 구현
  controllers/promising-controller.ts
  services/category-service.ts
Labels: ✨ FEAT

#46 [43-FEAT] 확정된 약속 조회 관련 기능 구현
  .eslintrc.json
  app.ts
  controllers/promise-controller.ts
  dtos/promise/response.ts
  services/promise-service.ts
  services/promise-user-service.ts
  services/promising-service.ts
  utils/time.ts
Labels: ✨ FEAT

#55 [47-BUG] Re : 약속 제안에 가능한 시간 응답 체크
  controllers/promising-controller.ts
  dtos/promising/request.ts
  dtos/promising/response.ts
  dtos/time/request.ts
  models/promising.ts
  services/event-service.ts
  services/promising-date-service.ts
  services/promising-service.ts
  services/time-service.ts
  utils/time.ts
Labels: 🐞 BUG, 🚧 REFACTOR

#56 [50-FEAT] 응답 가능한 날짜 관련 추가 수정 및 타임 테이블 응답 형식 변경
  controllers/promising-controller.ts
  dtos/event/request.ts
  dtos/event/response.ts
  dtos/promising/request.ts
  dtos/promising/response.ts
  dtos/time/request.ts
  dtos/time/response.ts
  services/promising-date-service.ts
  services/promising-service.ts
  utils/time.ts
  utils/type.ts
Labels: 🚧 REFACTOR, ✨ FEAT

#59 [58-FEAT] 확정된 약속 상세 조회
  controllers/promise-controller.ts
  services/promise-service.ts
  services/promise-user-service.ts
Labels: ✨ FEAT

#62 [16-DOCS] 약속 제안 관련 스웨거 문서 작성
  controllers/promising-controller.ts
  dtos/promising/request.ts
  dtos/promising/response.ts
  dtos/time/request.ts
  services/promising-date-service.ts
  services/promising-service.ts
Labels: 📄 DOCS

#64 [63-FEAT] 카테고리별 랜덤 이름 조회 API 구현
  .sequelizerc
  constants/category-name.json
  controllers/promising-controller.ts
  dtos/category/response.ts
  package.json
  seeders/20220715143124-category-keyword.ts
  services/category-service.ts
  swagger/openapi.yaml
  utils/error.ts
Labels: ✨ FEAT

#65 [57-FEAT] 약속 제안 불참 (모두 바빠요) 처리 개선
  controllers/promising-controller.ts
  dtos/event/request.ts
  dtos/event/response.ts
  dtos/promising/response.ts
  dtos/time/request.ts
  services/event-service.ts
  services/promise-service.ts
  services/promising-service.ts
  services/time-service.ts
Labels: 🚧 REFACTOR, ✨ FEAT

#71 [70-FEAT] 업데이트 시간 정보 추가 및 정렬 처리
  controllers/promising-controller.ts
  dtos/promising/response.ts
  services/promising-service.ts
  utils/time.ts
Labels: 🐞 BUG, ✨ FEAT

#74 [72-FEAT&73-FEAT] 사용자 정보 조회 API 추가 및 약속 제안 조회시 응답/주최자 여부 필드 추가
  constants/number.ts
  controllers/promising-controller.ts
  controllers/user-controller.ts
  dtos/promising/response.ts
  services/promising-service.ts
Labels: 🐞 BUG, ✨ FEAT

#69 [66-FEAT] 사용자 탈퇴 구현
  constants/nums.ts
  controllers/promising-controller.ts
  controllers/user-controller.ts
  services/event-service.ts
  services/promise-service.ts
  services/promise-user-service.ts
  services/promising-service.ts
  services/user-service.ts
Labels: ✨ FEAT

#76 [75-FEAT] 확정된 약속 목록 정렬 및 약속 제안 응답 가능 최대 일자 변경
  constants/color-index.json
  constants/number.ts
  controllers/promising-controller.ts
  dtos/promising/response.ts
  services/promise-service.ts
  services/promising-service.ts
Labels: 🐞 BUG, ✨ FEAT

#78 [77-FEAT] 사용자 이름 변경 API 구현
  controllers/promising-controller.ts
  controllers/user-controller.ts
  dtos/user/request.ts
  services/user-service.ts
Labels: ✨ FEAT

#80 [79-FEAT] 약속 제안 상태 조회 API 구현
  controllers/promising-controller.ts
  dtos/promising/response.ts
  services/promising-service.ts
  utils/type.ts
Labels: ✨ FEAT
